name: Test, compile and push client and server to staging

on:
  push:
    branches: ["staging"]
  workflow_dispatch:

jobs:
  build-and-push-server:
    uses: WildCodeSchool/2023-09-wns-bleu-hygi-checker/.github/workflows/build-backend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: hygichecker/hygi-checker-back

  build-and-push-client:
    uses: WildCodeSchool/2023-09-wns-bleu-hygi-checker/.github/workflows/build-frontend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: hygichecker/hygi-checker-front

  notify-vps:
    needs:
      - build-and-push-client
      - build-and-push-server
    runs-on: ubuntu-latest
    steps:
      - name: Call VPS webhook to update staging
        uses: wei/curl@master
        with:
          args: https://ops.0923-bleu-2.wns.wilders.dev/hooks/update-staging-hygi-checker"
